// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo-EyrI6r7cl0-vUTvsKz1o8L_IIGd2rU',
    appId: '1:569735370427:web:d787a2cd8a49d48106fb9e',
    messagingSenderId: '569735370427',
    projectId: 'pass-it-on-f3bf1',
    authDomain: 'pass-it-on-f3bf1.firebaseapp.com',
    databaseURL: 'https://pass-it-on-f3bf1-default-rtdb.firebaseio.com',
    storageBucket: 'pass-it-on-f3bf1.firebasestorage.app',
    measurementId: 'G-SP70YTR3ZS',
  );

  // 🌐 Web

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4exrf0ASOJdMkKziu9e15FM_M88g2Nms',
    appId: '1:569735370427:android:29fcbb2dcd51891206fb9e',
    messagingSenderId: '569735370427',
    projectId: 'pass-it-on-f3bf1',
    databaseURL: 'https://pass-it-on-f3bf1-default-rtdb.firebaseio.com',
    storageBucket: 'pass-it-on-f3bf1.firebasestorage.app',
  );

  // 🤖 Android

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxLHV0oPv7T_0RbJME9gfa-CTjSnRpcMA',
    appId: '1:569735370427:ios:6c2867a8a61578e306fb9e',
    messagingSenderId: '569735370427',
    projectId: 'pass-it-on-f3bf1',
    databaseURL: 'https://pass-it-on-f3bf1-default-rtdb.firebaseio.com',
    storageBucket: 'pass-it-on-f3bf1.firebasestorage.app',
    iosClientId: '569735370427-tlfj3cnnql8rmtltfg2alp4vid490ksl.apps.googleusercontent.com',
    iosBundleId: 'com.example.passiton',
  );

  // 🍎 iOS

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxLHV0oPv7T_0RbJME9gfa-CTjSnRpcMA',
    appId: '1:569735370427:ios:6c2867a8a61578e306fb9e',
    messagingSenderId: '569735370427',
    projectId: 'pass-it-on-f3bf1',
    databaseURL: 'https://pass-it-on-f3bf1-default-rtdb.firebaseio.com',
    storageBucket: 'pass-it-on-f3bf1.firebasestorage.app',
    iosClientId: '569735370427-tlfj3cnnql8rmtltfg2alp4vid490ksl.apps.googleusercontent.com',
    iosBundleId: 'com.example.passiton',
  );

  // 🍏 macOS

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo-EyrI6r7cl0-vUTvsKz1o8L_IIGd2rU',
    appId: '1:569735370427:web:405fc39ddd15842706fb9e',
    messagingSenderId: '569735370427',
    projectId: 'pass-it-on-f3bf1',
    authDomain: 'pass-it-on-f3bf1.firebaseapp.com',
    databaseURL: 'https://pass-it-on-f3bf1-default-rtdb.firebaseio.com',
    storageBucket: 'pass-it-on-f3bf1.firebasestorage.app',
    measurementId: 'G-LX9ERKHJSB',
  );

  // 🪟 Windows
}